# Generated by Django 3.2.8 on 2022-01-12 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('pub_date', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^[0-9-]*$', 'Only date format YYYY-MM are allowed .')])),
                ('isbn', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characters are allowed.')])),
                ('pages_number', models.PositiveIntegerField()),
                ('link_url', models.URLField()),
                ('pub_language', models.CharField(choices=[('pl', 'pl'), ('en', 'en'), ('it', 'it'), ('de', 'de'), ('es', 'es')], max_length=100)),
            ],
        ),
    ]
